init:
 - appveyor version
 - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
#- sh: export PATH="$PATH:${HOME}/.rbenv/bin"
- sh: echo $PATH
- sh: rbenv versions
- sh: |
    [[ -s "$HOME/.rbenv/bin/rbenv" ]]
    RUBY_VERSTIONS=($RUBY_VERSIONS)
    for v in "${RUBY_VERSIONS[@]}"; do
        rbenv local ${v} &&
        ruby --version ||
            { echo "[ERROR] Cannot use ${v}." 1>&2; exit 1;}
    done

build: off
